default_context:
  chart_name: "bigearthnet"
  chart_namespace: "test-bigearthnet"
  chart_version: "0.1.2"
  need_dep_chart: "no"
  include_service: "no"
  include_inference_service: "no"
  include_sklearn_inference_service: "no"
  include_namespace: "yes"
  include_role: "yes"
  include_role_binding: "yes"
  include_service_account: "no"
  include_virtual_service: "no"
  virtual_service_cluster_domain: "cineca-inference-server"
  include_sklearn_virtual_service: "no"
  include_external_s3_secret: "no"
  include_external_registry_secret: "no"